services:
  cms_postgres:
    image: postgres:15
    container_name: cms_postgres
    environment:
      POSTGRES_USER: cms_user
      POSTGRES_PASSWORD: KsNj237&Y87#T_123
      POSTGRES_DB: cms_db
    volumes:
      - cms_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - cms

  cms_web:
    container_name: cms_web
    build:
      context: .
      dockerfile: Dockerfile
    image: cms_web:latest
    command: >
      sh -c "
      python manage.py collectstatic --no-input &&
      gunicorn --bind 0.0.0.0:8000 base.wsgi:application
      "
    environment:
      - DEBUG=False
      - SECRET_KEY=django-insecure-^+t=^=p%qdx67&2^aecij2ppzb8a^xpim$$gh!!m-fhwe#4!v$
      - ALLOWED_HOSTS=cms.anwarhosen.xyz
      - DATABASE_URL=postgres://cms_user:KsNj237&Y87#T_123@cms_postgres:5432/cms_db
      - EMAIL_HOST_USER=
      - EMAIL_HOST_PASSWORD=
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - cms_postgres
    expose:
      - "8000"
    networks:
      - cms

  cms_nginx:
    image: nginx:alpine
    container_name: cms_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    depends_on:
      - cms_web
    restart: unless-stopped
    networks:
      - cms

volumes:
  cms_postgres_data:
    name: cms_postgres_data

networks:
  cms:
    name: cms
    driver: bridge
