# Generated by Django 5.2.1 on 2025-05-30 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('model', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(choices=[('REF', 'Refrigerator'), ('FREEZER', 'Deep Freezer'), ('TV', 'Television'), ('AC', 'Air Conditioner'), ('WM', 'Washing Machine'), ('OVEN', 'Microwave Oven'), ('SM', 'Sewing Machine'), ('COM', 'Computer'), ('OTHER', 'Others')], default=('REF', 'Refrigerator'), max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_num', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('closed', 'Closed')], max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Notes about this account', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acc_num'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_price', models.PositiveIntegerField(blank=True, null=True)),
                ('hire_price', models.PositiveIntegerField(blank=True, null=True)),
                ('down_payment', models.PositiveIntegerField()),
                ('monthly_payment', models.PositiveIntegerField(blank=True, null=True)),
                ('tenure', models.PositiveIntegerField(default=12)),
                ('cash_bal', models.IntegerField(blank=True, null=True)),
                ('hire_bal', models.IntegerField(blank=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='cms.account')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uid', models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(help_text='Enter 11 digit phone number', max_length=11)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uid'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='cms.customer'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('receipt_id', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cms.contract')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.product'),
        ),
    ]
