# Generated by Django 5.2.1 on 2025-05-30 21:30

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='cash_bal',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='hire_bal',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='uid',
        ),
        migrations.AddField(
            model_name='contract',
            name='total_paid',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='cms.customer'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='account',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.product'),
        ),
        migrations.AlterField(
            model_name='account',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('closed', 'Closed')], db_index=True, default=('planned', 'Planned'), max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='Enter 11 digit phone number', max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid 11-digit Bangladeshi phone number.', regex='^01[3-9][0-9]{8}$')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
