# Generated by Django 5.2.1 on 2025-05-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_customer_options_remove_contract_cash_bal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('closed', 'Closed')], db_index=True, default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='cash_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='contract',
            name='hire_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_paid',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('REF', 'Refrigerator'), ('FREEZER', 'Deep Freezer'), ('TV', 'Television'), ('AC', 'Air Conditioner'), ('WM', 'Washing Machine'), ('OVEN', 'Microwave Oven'), ('SM', 'Sewing Machine'), ('COM', 'Computer'), ('OTHER', 'Others')], default='REF', max_length=50),
        ),
    ]
