# Generated by Django 5.2.1 on 2025-06-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_account_status_alter_contract_cash_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='Enter 11 digit phone number', max_length=11),
        ),
    ]
